### ISSUE TITLE
How to use multiple orderBy

### ISSUE THREAD

**Issue by hansen1416** [rinvex/repository#114] opened 2016-11-23 06:55 UTC
It's simple.

When I use ->orderBy('sort', 'ASC')->orderBy('tier', 'ASC'), It seems only the last one is working, and previous one has been overridden. Wonder if there is any work around.

Thanks in advance!

**Comment by noxify** [comment] 2016-11-23 12:54
Hi,

i think this currently not possible, see this one:
https://github.com/rinvex/repository/blob/master/src/Repositories/BaseRepository.php#L380

Current workaround... create your own Repository... extend the existing one (BaseRepository or EloquentRepository) and overwrite the `orderBy` functionality :)

**Comment by hansen1416** [comment] 2016-11-24 06:18
@noxify Thanks a lot!

Looks like I have to do it by my self. Hope the author will add those new feature any time soon, it's a nice repo.

**Comment by noxify** [comment] 2016-11-24 13:37
If you found a solution - send a PR :) I think I need it also very soon :)

**Comment by Omranic** [comment] 2016-11-24 16:35
Well, after looking into this it seem that current implementation isn't quite right, so I guess your way is the intended behavior 👌 To be implemented, of course PR always welcome 🙂

**Comment by ionut-tanasa** [comment] 2016-12-09 22:40
#117 adds support to it. @Omranic  keen to merge it?

**Comment by Omranic** [comment] 2016-12-11 01:49
#117 merged, thanks guys for pushing forward 👍

**Closed by Omranic** 2016-12-11 01:49 UTC
